name: CocoaPods Blog
description: Updates for the fascinating developments happening in the CocoaPods world.
url: http://blog.cocoapods.org

markdown: redcarpet
pygments: true
permalink: /:title
exclude: ['Gemfile*', 'rakefile.rb', 'README.md', 'shared', 'vendor']
paginate: 10


github_pr_url: https://github.com/CocoaPods/blog.cocoapods.org/tree/master/

authors:
  eloy:
    name: Eloy Durán
    twitter: alloy
    gravatar: 424a9ce662b059c35063b405e160461d

  fabio:
    name: Fabio Pelosin
    twitter: fabiopelosin
    gravatar: b6dde1a78e6215a592768c1e78a54adc

  florian:
    name: Florian Hanke
    twitter: hanke
    gravatar: de2d64478e715fb02266f77a3f5641f6

  keith:
    name: Keith Smiley
    twitter: SmileyKeith
    gravatar: 6ab7ae85b84ebb323fab427b11500742

  kyle:
    name: Kyle Fuller
    twitter: kylefuller
    gravatar: d200a17dd269fd4001bacb11662dab4b

  michele:
    name: Michele Titolo
    twitter: micheletitolo
    gravatar: 88f93b77b71da10f57749166f7a94716

  orta:
    name: Orta Therox
    twitter: orta
    gravatar: f116cb3be23153ec08b94e8bd4dbcfeb

  boris:
    name: Boris Bügling
    twitter: NeoNacho
    gravatar: 66d863ad05a1af75a0e3c5cedc816943

  samuel:
    name: Samuel E. Giddins
    twitter: segiddins
    gravatar: 4d6be90af74894fd132fb06dacec04d7

  marius:
    name: Marius Rackwitz
    twitter: mrackwitz
    gravatar: ca018f2258eadef2d02f5dcea5c25b88

  hugo:
    name: Hugo Tunius
    twitter: K0nserv
    gravatar: 0301339c7b91dfc95a263eb27e6fe371

assets:
  sources:
    - shared/img
    - shared/fonts
    - shared/js
    - shared/sass
